//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WvacWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class loan
    {
        public long id { get; set; }
        public long UserID { get; set; }
        public string TypeOfLoan { get; set; }
        public long NoOfMonths { get; set; }
        public double LoanAmount { get; set; }
        public double AdvanceIntrest { get; set; }
        public double ServiceFee { get; set; }
        public double NotarialFee { get; set; }
        public double CBU { get; set; }
        public Nullable<double> Balance { get; set; }
        public double MonthlyDue { get; set; }
        public System.DateTime DateRelease { get; set; }
        public System.DateTime DateDue { get; set; }
        public Nullable<System.DateTime> SchedDate { get; set; }
        public string Status { get; set; }
    }
}
