//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WVACWebServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class loanpayment
    {
        public long ID { get; set; }
        public long LoanId { get; set; }
        public double Interest { get; set; }
        public double Fine { get; set; }
        public double AmountPaid { get; set; }
        public System.DateTime PayDate { get; set; }
    }
}
