//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WVACWebServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mempayment
    {
        public long ID { get; set; }
        public long memID { get; set; }
        public System.DateTime payDate { get; set; }
        public double fine { get; set; }
        public double amountPaid { get; set; }
        public double cash { get; set; }
        public double change { get; set; }
    }
}
